books/Controllers/BooksController.cs
using System.Globalization;
using AutoMapper;
using books.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using books.Data;
using books.Extensions;
using books.Models;
using books.Models.DTO;
using books.Models.ViewModels.BookModel;

namespace books.Controllers
{
    public class BooksController : Controller
    {
        private readonly BookContext _context;
        private readonly ILogger _logger;

        private readonly IMapper _mapper;
        public BooksController(BookContext context,
            ILoggerFactory factory,
            IMapper mapper,
            IWebHostEnvironment webHostEnvironment)
        {
            _webHostEnvironment = webHostEnvironment;
            _context = context;
            _mapper = mapper;
            _logger = factory.CreateLogger<BooksController>();
        }


        private void _checkAccess()
        {
            ViewBag.IsAdmin = User.Claims.Any(c => c.Type is Claims.Admin or Claims.SuperAdmin);
        }
        // GET: Books
        public async Task<IActionResult> Index(int genreId, int authorId, string? search)
        {
            _checkAccess();
            IQueryable<Book> bookContext = _context.Books
                    .Include(b => b.Author)
                    .Include(b => b.Genre)
                    .Include(b => b.Tags)

                ;
            if (genreId > 0)
            {
                bookContext = bookContext.Where(b => b.GenreId == genreId);
            }

            if (authorId > 0)
            {
                bookContext = bookContext.Where(b => b.AuthorId == authorId);
            }

            if (search != null)
            {
                bookContext = bookContext.Where(b => b.Title.Contains(search) ||
                                                     b.Tags.AsEnumerable()
                                                         .Any(t =>
                                                             t.Name.Contains(search)));

            }

            IEnumerable<GenreDTO> genreDtos = _mapper.Map<IEnumerable<GenreDTO>>(await _context.Genres.ToListAsync());
            IEnumerable<AuthorDTO> authorDtos = _mapper.Map<IEnumerable<AuthorDTO>>(await _context.Authors.ToListAsync());

            IEnumerable<BookDTO> bookDtos = _mapper.Map<IEnumerable<BookDTO>>(bookContext);

            SelectList genreList = new SelectList(items: genreDtos, dataValueField: "Id", dataTextField: "Name", selectedValue: genreId);
            SelectList authorList = new SelectList(items: authorDtos, dataValueField: "Id", dataTextField: "FullName", selectedValue: authorId);

            IndexBookViewModel vm = new IndexBookViewModel
            {
                Books = bookDtos,
                GenreSelect = genreList,
                AuthorSelect = authorList
            };
            return View(vm);
        }

        // GET: Books/Details/5
        public async Task<IActionResult> Details(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var book = _context.Books
                    .Include(b => b.Author)
                    .Include(b => b.Genre)
                    .Include(b => b.Tags)
                    .FirstOrDefault(b => b.Id == id);

            HttpContext.Session.Set<Book>("LastViewedBook" + book.Id, book);
            

            DetailsBookModel vm = new DetailsBookModel()
            {
                Book = _mapper.Map<BookDTO>(book)
            };

            return View(vm);

        }

        // GET: Books/Create
        public async Task<IActionResult> Create()
        {
            IEnumerable<GenreDTO> genreDtos = _mapper.Map<IEnumerable<GenreDTO>>(await _context.Genres.ToListAsync());
            IEnumerable<AuthorDTO> authorDtos = _mapper.Map<IEnumerable<AuthorDTO>>(await _context.Authors.ToListAsync());

            SelectList genreList = new SelectList(items: genreDtos, dataValueField: "Id", dataTextField: "Name");
            SelectList authorList = new SelectList(items: authorDtos, dataValueField: "Id", dataTextField: "FullName");
            CreateBookModel vm = new CreateBookModel
            {
                GenreList = genreList,
                AuthorList = authorList
            };


            return View(vm);
        }

        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateBookModel viewModel)
        {
            if (ModelState.IsValid)
            {
                viewModel.Book.CoverPath = await _coverUpload(viewModel.Cover);
                if (viewModel.Tags != null)
                {
                    viewModel.Book.Tags = await _handleTags(viewModel.Tags);
                }
                Book book = _mapper.Map<Book>(viewModel.Book);
                await _context.AddAsync(book);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                IEnumerable<GenreDTO> genreDtos = _mapper.Map<IEnumerable<GenreDTO>>(await _context.Genres.ToListAsync());
                IEnumerable<AuthorDTO> authorDtos = _mapper.Map<IEnumerable<AuthorDTO>>(await _context.Authors.ToListAsync());

                SelectList genreList = new SelectList(items: genreDtos, dataValueField: "Id", dataTextField: "Name", selectedValue: viewModel.Book.GenreId);
                SelectList authorList = new SelectList(items: authorDtos, dataValueField: "Id", dataTextField: "FullName");
                viewModel.AuthorList = authorList;
                viewModel.GenreList = genreList;
                foreach (var modelError in ModelState.Values.SelectMany(e => e.Errors))
                {
                    _logger.LogError(modelError.ErrorMessage);
                }

                return View(viewModel);
            }
        }
        
        private async Task<List<Tag>> _handleTags(IEnumerable<string>? tags)
        {
            return tags.Select(tag =>
                    _context.Tags.AsEnumerable().FirstOrDefault(t =>
                        string.Compare(t.Name, tag, StringComparison.CurrentCultureIgnoreCase) == 0)
                ??
                    new Tag
                    {
                        Name = CultureInfo.CurrentCulture
                .TextInfo.ToTitleCase(tag.ToLower())
                    })
                .ToList();
        }


        private IWebHostEnvironment _webHostEnvironment;
        private async Task<string> _coverUpload(IFormFile? file)
        {
            if (file == null)
                return "";
            var uniqueFileName = Guid.NewGuid() + "_" + file.FileName;
            var filePath = Path.Combine("img", uniqueFileName);
            await using var fileStream = new FileStream(Path.Combine(_webHostEnvironment.WebRootPath, filePath), FileMode.Create);
            await file.CopyToAsync(fileStream);
            return filePath;
        }
        // GET: Books/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Books == null)
            {
                return NotFound();
            }

            var book = _context.Books
                .Include(b => b.Tags)
                .FirstOrDefault(b => b.Id == id);
            if (book == null)
            {
                return NotFound();
            }
            IEnumerable<GenreDTO> genreDtos = _mapper.Map<IEnumerable<GenreDTO>>(await _context.Genres.ToListAsync());
            IEnumerable<AuthorDTO> authorDtos = _mapper.Map<IEnumerable<AuthorDTO>>(await _context.Authors.ToListAsync());

            SelectList genreList = new SelectList(items: genreDtos, dataValueField: "Id", dataTextField: "Name");
            SelectList authorList = new SelectList(items: authorDtos, dataValueField: "Id", dataTextField: "FullName");
            var vm = new EditBookModel()
            {
                Book = _mapper.Map<BookDTO>(book),
                GenreList = genreList,
                AuthorList = authorList
            };


            return View(vm);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, EditBookModel viewModel)
        {
            if (id != viewModel.Book.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {

                    if (viewModel.Tags != null && viewModel.Tags.Any())
                    {
                        var b = _context.Books.Include(b => b.Tags).FirstOrDefault(b => b.Id == id);
                        if (b != null) 
                            b.Tags = await _handleTags(viewModel.Tags);
                    }


                    if (viewModel.Cover != null)
                    {
                        _deleteFile(viewModel.Book.CoverPath);
                        viewModel.Book.CoverPath = await _coverUpload(viewModel.Cover);
                    }
                    var book = _mapper.Map<Book>(viewModel.Book);

                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookExists(viewModel.Book.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

books/Controllers/GenresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using books.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using books.Data;
using books.Models;

namespace books.Controllers
{
    public class GenresController : Controller
    {
        private readonly BookContext _context;

        public GenresController(BookContext context)
        {
            _context = context;
        }


        private void _checkAccess()
        {
            ViewBag.IsAdmin = User.Claims.Any(c => c.Type is Claims.Admin or Claims.SuperAdmin);
        }
        // GET: Genres
        public async Task<IActionResult> Index()
        {
            _checkAccess();
            return View(await _context.Genres.ToListAsync());
        }

        // GET: Genres/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Genres == null)
            {
                return NotFound();
            }

            var genre = await _context.Genres
                .FirstOrDefaultAsync(m => m.Id == id);
            if (genre == null)
            {
                return NotFound();
            }

            return View(genre);
        }

        // GET: Genres/Create
        public IActionResult Create()
        {
            return View();
        }

        
        // POST: Genres/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Genre genre)
        {
            if (ModelState.IsValid)
            {
                _context.Add(genre);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(genre);
        }

        // GET: Genres/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Genres == null)
            {
                return NotFound();
            }

            var genre = await _context.Genres.FindAsync(id);
            if (genre == null)
            {
                return NotFound();
            }
            return View(genre);
        }

        // POST: Genres/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Genre genre)
        {
            if (id != genre.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(genre);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GenreExists(genre.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(genre);
        }

        // GET: Genres/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Genres == null)
            {
                return NotFound();
            }

            var genre = await _context.Genres
                .FirstOrDefaultAsync(m => m.Id == id);
            if (genre == null)
            {
                return NotFound();
            }

            return View(genre);
        }

        // POST: Genres/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {

            if (_context.Genres == null)
            {
                return Problem("Entity set 'BookContext.Genres'  is null.");
            }
            var genre = await _context.Genres.FindAsync(id);
            if (genre != null)
            {
                _context.Genres.Remove(genre);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GenreExists(int id)
        {
            return _context.Genres.Any(e => e.Id == id);
        }
    }
}

books/Views/Shared/_Layout.cshtml
@using books.Authorization
@using Microsoft.AspNetCore.Mvc.TagHelpers
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - books</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/books.styles.css" asp-append-version="true" />
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a href="/" class="btn btn-light"><i class="fas fa-home"></i></a>

                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="Index">Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Authors" asp-action="Index">Authors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Genres" asp-action="Index">Genres</a>
                        </li>

                    </ul>
                </div>
                <div>
                    <ul class="navbar-nav ml-auto">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item bg-light rounded rounded-1">
                                <div class="nav-link text-primary rounded rounded-1 bg-gradientme-3">
                                    @if (User.HasClaim(c => c.Type == "SuperAdmin"))
                                    {
                                        <a class="nav-link text-primary btn btn-sm btn-outline-info" asp-area="" asp-controller="SuperAdmin" asp-action="ManageUsersClaims">
                                            @User.Identity.Name
                                        </a>
                                    }
                                    else
                                    {
                                        <a class="nav-link text-primary btn btn-sm btn-outline-info" asp-area="" asp-controller="Account" asp-action="Cabinet">
                                            @User.Identity.Name
                                        </a>
                                    }
                                </div>
                            </li>
                          
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                            </li>

                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - books
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>