books/Controllers/SuperAdminController.cs
using System.Security.Claims;
using books.Authorization;
using books.Models;
using books.Models.ViewModels.SuperAdminViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace books.Controllers
{
    public class SuperAdminController : Controller
    {
        private readonly UserManager<User> _userManager;

        public SuperAdminController(UserManager<User> userManager)
        {
            _userManager = userManager;
        }
        [Authorize(Policy = Policies.SuperAdminAccessOnly)]
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public async Task<ActionResult<IEnumerable<User>>> ManageUsersClaims()
        {
            User currentUser = await _userManager.GetUserAsync(User);
            if (currentUser == null)
                return Unauthorized();
            IQueryable<User> users = _userManager.Users
                .Where(u => u.EmailConfirmed == true && u.Id != currentUser.Id);
            IList<UserAccessVm> accessVm = new List<UserAccessVm>();
            foreach (var user in users)
            {
                var vm = new UserAccessVm();
                IList<Claim> userClaims = await _userManager.GetClaimsAsync(user);
                if (userClaims.Any(c => c.Type == Claims.Admin))
                {
                    vm.Access = Access.Admin;
                }
                else if (userClaims.Any(c => c.Type == Claims.Member))
                {
                    vm.Access = Access.Member;
                }
                else
                {
                    vm.Access = Access.None;
                }

                vm.Email = user.Email;
                accessVm.Add(vm);

            }
            return View(accessVm);
        }

        [HttpPost]
        public async Task<ActionResult> ManageUsersClaims(List<UserAccessVm> userAccessVms)
        {
            ViewBag.Message = null;
            foreach (var userAccessVm in userAccessVms)
            {
                var user = await _userManager.Users
                    .FirstOrDefaultAsync(u => u.Email == userAccessVm.Email);
                if (user == null)
                    continue;
                IList<Claim> useClaims = await _userManager.GetClaimsAsync(user);
                await _userManager.RemoveClaimsAsync(user, useClaims);
                switch (userAccessVm.Access)
                {
                    case Access.Admin:
                        await _userManager.AddClaimAsync(user,Claims.AdminClaim);
                        break;
                    case Access.Member:
                        await _userManager.AddClaimAsync(user, Claims.MemberClaim);
                        break;
                }
            }

            ViewBag.Message = "Success";
            return View(userAccessVms);
        }
    }
}

books/Views/SuperAdmin/Index.cshtml
@{
    Layout = "_SuperAdminLayout";
}
<h2>Index</h2>
<script>
    document.addEventListener("DOMContentLoaded"
        , () => {
            document.getElementById("superAdminMenuId1").classList.add("active");
            document.getElementById("superAdminMenuId1").classList.add("bg-info");
            document.getElementById("superAdminMenuId1").classList.add("rounded");
            document.getElementById("superAdminMenuId1").classList.add("rounded-1");
        });
</script>

books/Views/SuperAdmin/ManageUsersClaims.cshtml
@using books.Models.ViewModels.SuperAdminViewModel
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model IEnumerable<UserAccessVm>
@{
    Layout = "_SuperAdminLayout";
    int i = 0;
}
<form asp-action="ManageUsersClaims" method="post">
    @foreach (var user in Model)
    {
        <div class="bg-light border border-3 rounded rounded-3 p-2 mb-3">
            <div>
                <span class="fw-semibold">
                    @(user.Email).
                </span>
                Current access -
                <span class="fw-bold">
                    @user.Access.ToString()
                </span>
            </div>
            <div class="">
                @foreach (var access in Enum.GetValues(typeof(Access)))
                {
                    bool isChecked = user.Access.ToString() == access.ToString() ? true:false;<div class="form-check">
                                                                                                  <input name="[@i].managedAccess"
                                                                                                         id="access@(i)"
                                                                                                         type="radio"
                                                                                                         value="@access"
                                                                                                         checked="@isChecked"
                                                                                                         class="form-check-input">
                                                                                                  <label for="access@(i)"
                                                                                                         class="form-check-label">
                                                                                                      @access.ToString()
                                                                                                  </label>
                                                                                              </div>
                }
            </div>
            <input type="hidden" name="[@i].email" value="@user.Email"/>
        </div>
        i++;
    }
    <input type="submit" value="Manage Claims" class="btn btn-lg btn-warning rounded-1"/></form>
<script>
    document.addEventListener("DOMContentLoaded"
        , () => {
            document.getElementById("superAdminMenuId2").classList.add("active");
            document.getElementById("superAdminMenuId2").classList.add("bg-info");
            document.getElementById("superAdminMenuId2").classList.add("rounded");
            document.getElementById("superAdminMenuId2").classList.add("rounded-1");
        });
</script>

books/Views/SuperAdmin/_SuperAdminLayout.cshtml
@{
    Layout = "_Layout";
}
@if (ViewBag?.Message != null)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <i class="bi bi-bookmark-check-fill"></i>
        @ViewBag.Message
        <button type="button"
                class="btn-close"
                data-bs-dismiss="alert"
                aria-label="Close"></button>
    </div>
}
<nav class="navbar navbar-expand-lg bg-light mb-3">
<div class="container-fluid">
<a asp-action="Index"
   asp-controller="SuperAdmin"
   class="navbar-brand">Super Admin Panel</a>
<button class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarNavDropdown"
        aria-controls="navbarNavDropdown"
        aria-expanded="false"
        aria-label="nav switcher">
    <span class="navbar-toggler-icon"></span>
</button><div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a asp-action="ManageUsersClaims"
                   id="superAdminMenuId2"
                   class="nav-link" >Manage Users Claims</a>
            </li>
        </ul>
    </div>
</div>
</nav>
@*Here will be other pages*@
@RenderBody()