books/Models/DB Models/Book.cs
using System.ComponentModel.DataAnnotations;

namespace books.Models;

public class Book
{
    [Key]
    public int Id { get; set; }
    public string Title { get; set; } = default!;
    public int? AuthorId { get; set; } = default!;
    public Author? Author { get; set; }
    public int? GenreId { get; set; }
    public Genre? Genre { get; set; }
    public string Publishing { get; set; } = default!;
    public int PublicYear { get; set; }
    public string? CoverPath { get; set; } = default!;
    public List<Tag>? Tags { get; set; } = default!;
}

books/Components/LastViewedBookViewComponent.cs
using books.Extensions;
using books.Models;
using Microsoft.AspNetCore.Mvc;

namespace books.Components
{
    public class LastViewedBookViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            List<Book?> books = new List<Book?>();
            foreach (var key in HttpContext.Session.Keys.Where(k=> k.Contains("LastViewedBook")))
            {
                books.Add(HttpContext.Session.Get<Book>(key));
            }
            return View(books);
        }
    }
}

books/Controllers/BooksController.cs
using System.Globalization;
using AutoMapper;
using books.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using books.Data;
using books.Extensions;
using books.Models;
using books.Models.DTO;
using books.Models.ViewModels.BookModel;

namespace books.Controllers
{
    public class BooksController : Controller
    {
        private readonly BookContext _context;
        private readonly ILogger _logger;

        private readonly IMapper _mapper;
        public BooksController(BookContext context,
            ILoggerFactory factory,
            IMapper mapper,
            IWebHostEnvironment webHostEnvironment)
        {
            _webHostEnvironment = webHostEnvironment;
            _context = context;
            _mapper = mapper;
            _logger = factory.CreateLogger<BooksController>();
        }


        private void _checkAccess()
        {
            ViewBag.IsAdmin = User.Claims.Any(c => c.Type is Claims.Admin or Claims.SuperAdmin);
        }
        // GET: Books
        public async Task<IActionResult> Index(int genreId, int authorId, string? search)
        {
            _checkAccess();
            IQueryable<Book> bookContext = _context.Books
                    .Include(b => b.Author)
                    .Include(b => b.Genre)
                    .Include(b => b.Tags)

                ;
            if (genreId > 0)
            {
                bookContext = bookContext.Where(b => b.GenreId == genreId);
            }

            if (authorId > 0)
            {
                bookContext = bookContext.Where(b => b.AuthorId == authorId);
            }

            if (search != null)
            {
                bookContext = bookContext.Where(b => b.Title.Contains(search) ||
                                                     b.Tags.AsEnumerable()
                                                         .Any(t =>
                                                             t.Name.Contains(search)));

            }

            IEnumerable<GenreDTO> genreDtos = _mapper.Map<IEnumerable<GenreDTO>>(await _context.Genres.ToListAsync());
            IEnumerable<AuthorDTO> authorDtos = _mapper.Map<IEnumerable<AuthorDTO>>(await _context.Authors.ToListAsync());

            IEnumerable<BookDTO> bookDtos = _mapper.Map<IEnumerable<BookDTO>>(bookContext);

            SelectList genreList = new SelectList(items: genreDtos, dataValueField: "Id", dataTextField: "Name", selectedValue: genreId);
            SelectList authorList = new SelectList(items: authorDtos, dataValueField: "Id", dataTextField: "FullName", selectedValue: authorId);

            IndexBookViewModel vm = new IndexBookViewModel
            {
                Books = bookDtos,
                GenreSelect = genreList,
                AuthorSelect = authorList
            };
            return View(vm);
        }

        // GET: Books/Details/5
        public async Task<IActionResult> Details(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var book = _context.Books
                    .Include(b => b.Author)
                    .Include(b => b.Genre)
                    .Include(b => b.Tags)
                    .FirstOrDefault(b => b.Id == id);

            HttpContext.Session.Set<Book>("LastViewedBook" + book.Id, book);
            

            DetailsBookModel vm = new DetailsBookModel()
            {
                Book = _mapper.Map<BookDTO>(book)
            };

            return View(vm);

        }

        // GET: Books/Create
        public async Task<IActionResult> Create()
        {
            IEnumerable<GenreDTO> genreDtos = _mapper.Map<IEnumerable<GenreDTO>>(await _context.Genres.ToListAsync());
            IEnumerable<AuthorDTO> authorDtos = _mapper.Map<IEnumerable<AuthorDTO>>(await _context.Authors.ToListAsync());

            SelectList genreList = new SelectList(items: genreDtos, dataValueField: "Id", dataTextField: "Name");
            SelectList authorList = new SelectList(items: authorDtos, dataValueField: "Id", dataTextField: "FullName");
            CreateBookModel vm = new CreateBookModel
            {
                GenreList = genreList,
                AuthorList = authorList
            };


            return View(vm);
        }

        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateBookModel viewModel)
        {
            if (ModelState.IsValid)
            {
                viewModel.Book.CoverPath = await _coverUpload(viewModel.Cover);
                if (viewModel.Tags != null)
                {
                    viewModel.Book.Tags = await _handleTags(viewModel.Tags);
                }
                Book book = _mapper.Map<Book>(viewModel.Book);
                await _context.AddAsync(book);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                IEnumerable<GenreDTO> genreDtos = _mapper.Map<IEnumerable<GenreDTO>>(await _context.Genres.ToListAsync());
                IEnumerable<AuthorDTO> authorDtos = _mapper.Map<IEnumerable<AuthorDTO>>(await _context.Authors.ToListAsync());

                SelectList genreList = new SelectList(items: genreDtos, dataValueField: "Id", dataTextField: "Name", selectedValue: viewModel.Book.GenreId);
                SelectList authorList = new SelectList(items: authorDtos, dataValueField: "Id", dataTextField: "FullName");
                viewModel.AuthorList = authorList;
                viewModel.GenreList = genreList;
                foreach (var modelError in ModelState.Values.SelectMany(e => e.Errors))
                {
                    _logger.LogError(modelError.ErrorMessage);
                }

                return View(viewModel);
            }
        }
        
        private async Task<List<Tag>> _handleTags(IEnumerable<string>? tags)
        {
            return tags.Select(tag =>
                    _context.Tags.AsEnumerable().FirstOrDefault(t =>
                        string.Compare(t.Name, tag, StringComparison.CurrentCultureIgnoreCase) == 0)
                ??
                    new Tag
                    {
                        Name = CultureInfo.CurrentCulture
                .TextInfo.ToTitleCase(tag.ToLower())
                    })
                .ToList();
        }


        private IWebHostEnvironment _webHostEnvironment;
        private async Task<string> _coverUpload(IFormFile? file)
        {
            if (file == null)
                return "";
            var uniqueFileName = Guid.NewGuid() + "_" + file.FileName;
            var filePath = Path.Combine("img", uniqueFileName);
            await using var fileStream = new FileStream(Path.Combine(_webHostEnvironment.WebRootPath, filePath), FileMode.Create);
            await file.CopyToAsync(fileStream);
            return filePath;
        }
        // GET: Books/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Books == null)
            {
                return NotFound();
            }

            var book = _context.Books
                .Include(b => b.Tags)
                .FirstOrDefault(b => b.Id == id);
            if (book == null)
            {
                return NotFound();
            }
            IEnumerable<GenreDTO> genreDtos = _mapper.Map<IEnumerable<GenreDTO>>(await _context.Genres.ToListAsync());
            IEnumerable<AuthorDTO> authorDtos = _mapper.Map<IEnumerable<AuthorDTO>>(await _context.Authors.ToListAsync());

            SelectList genreList = new SelectList(items: genreDtos, dataValueField: "Id", dataTextField: "Name");
            SelectList authorList = new SelectList(items: authorDtos, dataValueField: "Id", dataTextField: "FullName");
            var vm = new EditBookModel()
            {
                Book = _mapper.Map<BookDTO>(book),
                GenreList = genreList,
                AuthorList = authorList
            };


            return View(vm);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, EditBookModel viewModel)
        {
            if (id != viewModel.Book.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {

                    if (viewModel.Tags != null && viewModel.Tags.Any())
                    {
                        var b = _context.Books.Include(b => b.Tags).FirstOrDefault(b => b.Id == id);
                        if (b != null) 
                            b.Tags = await _handleTags(viewModel.Tags);
                    }


                    if (viewModel.Cover != null)
                    {
                        _deleteFile(viewModel.Book.CoverPath);
                        viewModel.Book.CoverPath = await _coverUpload(viewModel.Cover);
                    }
                    var book = _mapper.Map<Book>(viewModel.Book);

                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookExists(viewModel.Book.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

books/Views/Books/Create.cshtml
@model CreateBookModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Book</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Book.Title" class="control-label"></label>
                <input asp-for="Book.Title" class="form-control" />
                <span asp-validation-for="Book.Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Book.AuthorId" class="control-label">Author</label>
                <select asp-for="Book.AuthorId" class="form-control" asp-items="@Model!.AuthorList">
                    <option selected="selected" disabled="disabled">Choose author</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Book.GenreId" class="control-label">Genre</label>
                <select asp-for="Book.GenreId" class="form-control" asp-items="@Model!.GenreList">
                    <option selected="selected" disabled="disabled">Choose Genre</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Book.Publishing" class="control-label"></label>
                <input asp-for="Book.Publishing" class="form-control" />
                <span asp-validation-for="Book.Publishing" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Book.PublicYear" class="control-label"></label>
                <input asp-for="Book.PublicYear" class="form-control" />
                <span asp-validation-for="Book.PublicYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cover" class="control-label"></label>
                <input asp-for="Cover" class="form-control" />
                <span asp-validation-for="Cover" class="text-danger"></span>
            </div>
            <div id="tag-inputs"></div>
            <div class="mb-3">
                <button type="button"
                        onclick="addNewTag()"
                        class="btn btn-primary">
                    Add Tag
                </button>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
            <div id="tag-container"></div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

<script src="/js/tags.js"></script>

books/Views/Books/Delete.cshtml
@model DeleteBookModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Book</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Book.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Book.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Book.Author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Book.Author.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Book.Genre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Book.Genre.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Book.Publishing)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Book.Publishing)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Book.PublicYear)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Book.PublicYear)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Book.CoverPath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Book.CoverPath)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Book.Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

books/Views/Books/Details.cshtml
@model DetailsBookModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>
<div class="card mb-3 w-100">
    <div class="row g-0">
        <div class="col-md-6">
            <img src="~/@Model.Book.CoverPath"
                 class="w-100"
                 alt="@Model.Book.Title">
        </div>
        <div class="col-md-6">
            <div class="card-body">
                <h4 class="card-title">@Model.Book.Title</h4>
                <p>
                    <span class="fw-bold">
                        @Html.DisplayNameFor(m => m.Book.Genre!)
                    </span>
                    @Model.Book.Genre!.Name
                </p>

                <p>
                    <span class="fw-bold">
                        @Html.DisplayNameFor(m => m.Book.Author)
                    </span>
                    @Model.Book.Author!.ToString();
                </p>

                <p class="card-text" style="white-space: pre-line">
                    <span class="fw-bold">
                        @Html.DisplayNameFor(m => m.Book.Publishing)
                    </span>
                    @Model.Book.Publishing @Model.Book.PublicYear
                </p>
                @if(Model.Book.Tags!=null)
                {
                    <ul class="list-group list-group-flush">
                        @foreach (var tag in Model.Book.Tags)
                        {
                            <li class="list-group-item list-group-item-action">@tag.Name</li>
                        }
                    </ul>
                        
                }
            </div>
        </div>
    </div>
</div>
<div>
    <a asp-action="Edit"
       asp-route-id="@Model.Book.Id"
       class="btn btn-warning me-3">Edit</a> |
    <a asp-action="Index"
       class="btn btn-primary ms-3">Back to List</a>
</div>

books/Views/Books/Edit.cshtml
@model EditBookModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Book</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Book.Id"/>
            <input type="hidden" asp-for="Book.CoverPath"/>

            <div class="form-group">
                <label asp-for="Book.Title" class="control-label"></label>
                <input asp-for="Book.Title" class="form-control" />
                <span asp-validation-for="Book.Title" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Book.AuthorId" class="control-label"></label>
                <select asp-for="Book.AuthorId" class="form-control" asp-items="@Model!.AuthorList">
                    <option selected="selected" disabled="disabled">Choose author</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Book.GenreId" class="control-label"></label>
                <select asp-for="Book.GenreId" class="form-control" asp-items="@Model!.GenreList">
                    <option selected="selected" disabled="disabled">Choose Genre</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Book.Publishing" class="control-label"></label>
                <input asp-for="Book.Publishing" class="form-control" />
                <span asp-validation-for="Book.Publishing" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Book.PublicYear" class="control-label"></label>
                <input asp-for="Book.PublicYear" class="form-control" />
                <span asp-validation-for="Book.PublicYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cover" class="control-label"></label>
                <input asp-for="Cover" class="form-control" />
                <span asp-validation-for="Cover" class="text-danger"></span>
            </div>
            <div id="tag-inputs">
                @if(@Model.Book.Tags.Any())
                {
                    int index = 0;
                    @foreach (var tag in @Model.Book.Tags)
                    {
                        <input type="hidden" asp-for="Book.Tags[index].Name" value="@tag.Name"/>

                        <partial name="_AddNewTagPartial" model="(@tag.Name)" />

                        index++;
                    }
                }
            </div>
            <div class="mb-3 mt-3">
                <button type="button"
                        onclick="addNewTag()"
                        class="btn btn-primary">
                    Add Tag
                </button>
            </div>
            <div class="form-group">
                <input type="submit" value="Edit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


<div>
    <a asp-action="Index">Back to List</a>
</div>

<script src="/js/tags.js"></script>

books/Views/Books/Index.cshtml
@model IndexBookViewModel

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

@if (User.Identity.IsAuthenticated)
{
    <p>
        <a asp-action="Create">Create New</a>
    </p>
}
<form asp-action="Index" method="get">
    <div class="row">
        <div class=" col col-md-4 col-12">
            <div class="mb-3">
                <label asp-for="GenreId">Genre</label>
                <select asp-for="GenreId" asp-items="@Model!.GenreSelect">
                    <option selected="selected" value="0">All</option>
                </select>
            </div>
        </div>
        <div class=" col col-md-4 col-12">
            <div class="mb-3">
                <label asp-for="AuthorId">Author</label>
                <select asp-for="AuthorId" asp-items="@Model.AuthorSelect">
                    <option selected="selected" value="0">All</option>
                </select>
            </div>
        </div>

        <div class=" col col-md-4 col-12">
            <div class="mb-3">
                <input asp-for="Search" class="form-control" placeholder="@nameof(Model.Search)" />
            </div>
        </div>
        <div class=" col col-md-4 col-12">
            <div class="mb-3">
                <button type="submit" class="btn-success">Search</button>
            </div>
        </div>
    </div>
</form>
<div class="row">
    @foreach (var book in Model.Books)
    {
        <div class="col col-xl-3 col-lg-4 col-md-6 col-12 mb-5">
            <div class="card mb-3">
                <div class="card-body">
                    <h2 class="card-title">@book.Title</h2>
                    <hr />
                    <h3 class="card-title">@book.Author?.ToString()</h3>
                    <h3 class="card-title">@book.Genre?.Name</h3>
                    <p class="card-text">Publishing: @book.Publishing @book.PublicYear</p>
                    @if (book.Tags != null)
                    {
                        <div>
                            <h3 class="card-title">Tags:</h3>
                            @foreach (var tag in book.Tags)
                            {
                                <span class="card-text">@tag.Name</span>
                            }
                        </div>

                    }
                    <div class="btn-group btn-group-sm">
                        @if (ViewBag.IsAdmin)
                        {
                            <a asp-action="Edit" asp-route-id="@book.Id" class="btn-success btn">Edit</a>
                            <a asp-action="Delete" asp-route-id="@book.Id" class="btn-danger btn">Delete</a>
                        }
                        <a asp-action="Details" asp-route-id="@book.Id" class="btn-warning btn ">Details</a>
                    </div>

                    <div class="card">
                        <img class="card-img-bottom" src="@book.CoverPath" alt="Cover" />
                    </div>
                </div>
            </div>
        </div>
    }
</div>

<vc:last-viewed-book/>

books/Views/Books/_AddNewTagPartial.cshtml
@model string
<div class="tag-input-container mt-3">
    <input type="text" name="Tags" class="form-control" placeholder="Enter a tag" value="@Model"/>
    <button onclick="deleteTag(event)" type="button" class="btn btn-danger tag-delete-button"><i class="fas fa-times"></i></button>
    <span class="text-danger"></span>
</div>
<script src="/js/deleteTag.js"></script>

books/Views/Books/_BooksViewedPartial.cshtml
@model Book
@using books.Authorization

<div class="col-sm-6 col-md-4 col-lg-3">
    
    <div class="card viewed-book" style="width: 18rem;">
        <img class="card-img-top img-fluid rounded" src="@Model.CoverPath" alt="Card image cap">
        <div class="card-body">
            <p class="card-title">
                <a asp-action="Details"
                   asp-route-id="@Model.Id"
                   class="text-decoration-none">@Model.Title</a>
            </p>
            <p class="card-title">@Model.Author?.ToString()</p>
            <p class="card-title">@Model.Genre?.Name</>
            <hr />
            <a asp-action="Details"
               asp-route-id="@Model.Id" class="btn btn-primary">Details</a>
        </div>
    </div>
    
</div>